create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  default_budget_minutes integer not null default 120,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  color text not null default '#475569',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, name)
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  category_id bigint not null references public.categories(id),
  priority text not null check(priority in ('high','medium','low')),
  status text not null check(status in ('not_started','active','paused','waiting','completed','cancelled')),
  budget_minutes integer not null,
  progress_percent integer not null default 0 check(progress_percent between 0 and 100),
  notes text not null default '',
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.time_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz not null,
  effective_seconds integer not null check(effective_seconds >= 0),
  pause_seconds integer not null default 0 check(pause_seconds >= 0),
  notes text not null default '',
  is_manual_adjusted boolean not null default false,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.active_timer (
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  state text not null check(state in ('running','paused')),
  started_at timestamptz not null,
  last_resumed_at timestamptz,
  paused_at timestamptz,
  accumulated_seconds integer not null default 0,
  accumulated_pause_seconds integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key(user_id, project_id)
);

create table if not exists public.settings (
  user_id uuid not null references auth.users(id) on delete cascade,
  key text not null,
  value_json jsonb not null,
  updated_at timestamptz not null default now(),
  primary key(user_id, key)
);

alter table public.active_timer drop constraint if exists active_timer_pkey;
alter table public.active_timer add constraint active_timer_pkey primary key(user_id, project_id);

alter table public.categories enable row level security;
alter table public.projects enable row level security;
alter table public.time_sessions enable row level security;
alter table public.active_timer enable row level security;
alter table public.settings enable row level security;

create policy "own categories" on public.categories for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own projects" on public.projects for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own sessions" on public.time_sessions for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own timer" on public.active_timer for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "own settings" on public.settings for all using (user_id = auth.uid()) with check (user_id = auth.uid());

create or replace function public.seed_content_workbench_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare other_id bigint; project_id bigint;
begin
  insert into categories(user_id,name,default_budget_minutes,sort_order,color) values
    (new.id,'内容制作',120,10,'#0F766E'),(new.id,'茶叶实务',120,20,'#3F7D20'),
    (new.id,'客户对接',120,30,'#7C3AED'),(new.id,'资料整理',120,40,'#2563A6'),
    (new.id,'学习研究',120,50,'#B45309'),(new.id,'运营事务',120,60,'#BE185D'),
    (new.id,'其他',120,70,'#475569');
  select id into other_id from categories where user_id=new.id and name='其他';
  insert into projects(user_id,name,category_id,priority,status,budget_minutes,progress_percent,notes,created_at,updated_at)
    values(new.id,'量化学习',other_id,'medium','active',60000,0,'','2026-08-07T03:02:54Z','2026-08-09T02:46:30Z') returning id into project_id;
  insert into time_sessions(user_id,project_id,started_at,ended_at,effective_seconds,pause_seconds,notes,is_manual_adjusted,created_at,updated_at) values
    (new.id,project_id,'2026-08-07T01:15:35Z','2026-08-07T03:27:58Z',7943,0,'',true,'2026-08-07T03:27:58Z','2026-08-07T03:28:28Z'),
    (new.id,project_id,'2026-08-07T03:28:47Z','2026-08-07T03:29:00Z',12,1,'',false,'2026-08-07T03:29:00Z','2026-08-07T03:29:00Z'),
    (new.id,project_id,'2026-08-09T02:24:09Z','2026-08-09T02:46:30Z',1341,0,'',false,'2026-08-09T02:46:30Z','2026-08-09T02:46:30Z');
  insert into settings(user_id,key,value_json) values(new.id,'display_name','"内容工作台"'::jsonb);
  return new;
end $$;

drop trigger if exists on_content_workbench_user_created on auth.users;
create trigger on_content_workbench_user_created after insert on auth.users
for each row execute procedure public.seed_content_workbench_user();

create or replace function public.timer_start(p_project_id bigint)
returns void language plpgsql security invoker as $$
begin
  if exists(select 1 from active_timer where user_id=auth.uid() and project_id=p_project_id) then raise exception '该项目已在计时'; end if;
  if not exists(select 1 from projects where id=p_project_id and user_id=auth.uid()) then raise exception '项目不存在'; end if;
  insert into active_timer(user_id,project_id,state,started_at,last_resumed_at,updated_at)
  values(auth.uid(),p_project_id,'running',now(),now(),now());
  update projects set status='active',updated_at=now() where id=p_project_id and user_id=auth.uid();
end $$;

drop function if exists public.timer_pause();
create or replace function public.timer_pause(p_project_id bigint)
returns void language plpgsql security invoker as $$
begin
  update active_timer set state='paused', accumulated_seconds=accumulated_seconds+extract(epoch from (now()-last_resumed_at))::integer,
    paused_at=now(),updated_at=now() where user_id=auth.uid() and project_id=p_project_id and state='running';
  if not found then raise exception '当前没有运行中的计时'; end if;
end $$;

drop function if exists public.timer_resume();
create or replace function public.timer_resume(p_project_id bigint)
returns void language plpgsql security invoker as $$
begin
  update active_timer set state='running', accumulated_pause_seconds=accumulated_pause_seconds+extract(epoch from (now()-paused_at))::integer,
    last_resumed_at=now(),paused_at=null,updated_at=now() where user_id=auth.uid() and project_id=p_project_id and state='paused';
  if not found then raise exception '当前没有暂停中的计时'; end if;
end $$;

drop function if exists public.timer_stop(text);
create or replace function public.timer_stop(p_project_id bigint, p_notes text default '')
returns void language plpgsql security invoker as $$
declare a active_timer%rowtype; effective integer;
begin
  select * into a from active_timer where user_id=auth.uid() and project_id=p_project_id;
  if not found then raise exception '当前没有计时'; end if;
  effective := a.accumulated_seconds;
  if a.state='running' then effective := effective+extract(epoch from (now()-a.last_resumed_at))::integer; end if;
  insert into time_sessions(user_id,project_id,started_at,ended_at,effective_seconds,pause_seconds,notes)
  values(auth.uid(),a.project_id,a.started_at,now(),effective,a.accumulated_pause_seconds,coalesce(p_notes,''));
  delete from active_timer where user_id=auth.uid() and project_id=p_project_id;
  update projects set updated_at=now() where id=a.project_id and user_id=auth.uid();
end $$;
